version: 3
tasks:
  auto-migrate:
    desc: "Auto migrate database"
    cmds:
      - go run . autoMigrate
  serve-api:
    desc: "Run the application"
    cmds:
      - go run . serveApi
  gen:
    desc: "Generate mocks"
    cmds:
      - go generate ./...
      - docker run -v "$PWD":/src -w /src vektra/mockery --all
  test:
    desc: "Run tests"
    cmds:
      - go test ./app/... -cover